version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    environment:
      - REDIS_PASSWORD=zaq1@WSX
      - REDIS_PORT=6379
      - REDIS_DATABASES=0
volumes:
  cache:
    driver: local